name: springbok
description: Springbok for Dart Library
dependencies:
  unittest: any
  compiler: '>= 0.2.4'
#  compiler:
#    path: ../../springbok/compiler/
  springbok_router:
    path: ../../springbok/springbok_router/
  http_server: any
  crypto: any